//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicalX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookedSeat
    {
        public int Id { get; set; }
        public Nullable<int> HospitalId { get; set; }
        public Nullable<int> BACCabin { get; set; }
        public Nullable<int> BNonACCabin { get; set; }
        public Nullable<int> BMaleWard { get; set; }
        public Nullable<int> BFemaleWard { get; set; }
        public Nullable<int> BICU { get; set; }
    }
}
