//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicalX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDoctorBooking
    {
        public int Id { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Time { get; set; }
        public string PName { get; set; }
        public string PAge { get; set; }
        public string PGen { get; set; }
        public string PMob { get; set; }
        public string PRefDoc { get; set; }
        public string PProblem { get; set; }
        public string PDetails { get; set; }
        public Nullable<int> DHospitalId { get; set; }
        public string DName { get; set; }
        public string DDesignation { get; set; }
        public Nullable<int> DSpeciality { get; set; }
        public string DMobile { get; set; }
        public string DHospitalName { get; set; }
        public string DSpecialityName { get; set; }
    }
}
