//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicalX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDonner
    {
        public int Id { get; set; }
        public int HospitalId { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public int Gender { get; set; }
        public string Mobile { get; set; }
        public int BloodGroup { get; set; }
        public string HospitalName { get; set; }
        public string BloodGroupName { get; set; }
        public string GenderName { get; set; }
    }
}
